name: cargo-test-zcashrpc-typegen

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull Image
      run: docker pull ghcr.io/zingolabs/zcashrpc:latest

    - name: Clone Quizface
      run: cd .. && git clone https://github.com/zingolabs/quizface.git 

    - name: Clone Zcrpctypegen
      run: cd .. && git clone https://github.com/zingolabs/zcrpctypegen.git

    - name: Run Tests
      run: >- 
       docker run 
       -v /home/runner/work/zcashrpc/zcashrpc:/zcashrpc
       -v /home/runner/work/zcashrpc/quizface:/quizface
       -v /home/runner/work/zcashrpc/zcrpctypegen:/zcrpctypegen
       ghcr.io/zingolabs/zcashrpc:latest
       bash -c "mv ./zcash/src/zcash-cli /usr/local/bin/zcash-cli
       && mv ./zcash/src/zcashd /usr/local/bin/zcashd
       && zcashd -daemon
       && cd ../quizface
       && cat lists/passing.txt | xargs cargo run
       && cd .. && ls -la"
